<?php
/**
 * Rizal Province Location Data
 * Contains all cities in Rizal and their corresponding barangays
 */

$rizal_locations = [
    "Angono" => [
        "postal_code" => "1930",
        "barangays" => [
            "Ampid",
            "Bagumbayan",
            "Binakayan",
            "Bukal",
            "Pag-asa",
            "Pinagbuhatan",
            "Pulo",
            "San Luis",
            "Santa Cruz",
            "Santo Domingo"
        ]
    ],
    "Antipolo" => [
        "postal_code" => "1870",
        "barangays" => [
            "Bagong Nayon",
            "Bagong Sikat",
            "Baras",
            "Barong-Barong",
            "Bintig",
            "Cainta",
            "Dela Paz",
            "Paciano Rizal",
            "Pittland",
            "Proper Antipolo",
            "San Jose",
            "San Roque",
            "Santa Cruz",
            "Santo Domingo",
            "Silangan"
        ]
    ],
    "Binangonan" => [
        "postal_code" => "1940",
        "barangays" => [
            "Banaba",
            "Binuclod",
            "Blaan",
            "Bugnay",
            "Bukal",
            "Caloocan",
            "Halang",
            "Harasan",
            "Macabud",
            "Mahabang Parang",
            "Malapad",
            "Maturog",
            "Nagtahan",
            "Pala-pala",
            "Paraiso",
            "Pasay",
            "Putatan",
            "Rosario",
            "Tabing Ilog"
        ]
    ],
    "Cainta" => [
        "postal_code" => "1900",
        "barangays" => [
            "Binantayan",
            "Buenavista",
            "Canlubang",
            "Halaran",
            "Hinulugang Taktak",
            "Hollowville",
            "Magdalo",
            "Malaking Pulo",
            "Paliparan",
            "Putho",
            "Rosario",
            "Sampaloc",
            "San Antonio",
            "San Juan",
            "Santo Niño",
            "Sapang Kantin",
            "Tagumpay",
            "Tayabas"
        ]
    ],
    "Cardona" => [
        "postal_code" => "1960",
        "barangays" => [
            "Ampid",
            "Arado",
            "Bakwayan",
            "Binukling",
            "Bukal",
            "Burgos",
            "Caliligawan",
            "Dulongbayan",
            "Karamihan",
            "Kawit",
            "Lilibang",
            "Luguid",
            "Maligaya",
            "Namukahan",
            "Paldang",
            "Poblacion",
            "Sablayan",
            "San Miguel",
            "Santa Cruz"
        ]
    ],
    "Jala-Jala" => [
        "postal_code" => "1950",
        "barangays" => [
            "Aplaya",
            "Bagong Bayan",
            "Bawing",
            "Bikil",
            "Dagat",
            "Lipak",
            "Masasa",
            "Naginhawa",
            "Pilapil",
            "Poctol",
            "Polo",
            "Pulo",
            "Sabang",
            "Sagao",
            "Sampal",
            "San Agustin",
            "San Isidro",
            "Santa Cruz"
        ]
    ],
    "Montalban" => [
        "postal_code" => "1860",
        "barangays" => [
            "Baras",
            "Banila",
            "Basao",
            "Bungad",
            "Dulong",
            "Hinulugang Taktak",
            "Karangatan",
            "Kayamanan",
            "Korbay",
            "Lucod",
            "Magdalo",
            "Paligsahan",
            "Pampang",
            "Pulong Gubat",
            "San Juan",
            "Santa Cruz",
            "Sapang Palay",
            "Tumana"
        ]
    ],
    "Morong" => [
        "postal_code" => "1880",
        "barangays" => [
            "Anumang Kahoy",
            "Bagong Sikat",
            "Balas",
            "Bancal",
            "Basid",
            "Batino",
            "Bigte",
            "Biyaya",
            "Bungo",
            "Ditay",
            "Hicaon",
            "Kiyas",
            "Landayan",
            "Libjo",
            "Limot",
            "Mascap",
            "Maylupa",
            "Nayod",
            "Paresite",
            "Patimon",
            "Pigtaasan",
            "Pito",
            "Putubalan",
            "Rosario",
            "Sakal",
            "Sapang Pakad",
            "Sulip",
            "Tablang",
            "Tala",
            "Tankalan",
            "Tiguman",
            "Toldo",
            "Tulisan"
        ]
    ],
    "Pililla" => [
        "postal_code" => "1970",
        "barangays" => [
            "Bangkahan",
            "Batingin",
            "Biyahe",
            "Bobongin",
            "Bukal",
            "Bulihan",
            "Bulud",
            "Bulusan",
            "Calingatan",
            "Casili",
            "Cauit",
            "Hukay",
            "Kalyasan",
            "Kalyang-Kalyang",
            "Kapunan",
            "Kasiglahan",
            "Kaybagal",
            "Kayumanggi",
            "Paku",
            "Palibot",
            "Pambahayan",
            "Pangako",
            "Panghihip",
            "Panginabang",
            "Paningkaban",
            "Panitikan",
            "Pansol",
            "Pantay",
            "Pangao",
            "Papisahan",
            "Payapa",
            "Payasin",
            "Payo",
            "Pining",
            "Pinusan",
            "Pisang",
            "Pitak",
            "Poblacion",
            "Pulang-Bato",
            "Pulanglupa",
            "Pulantubig",
            "Pule",
            "Pungao",
            "Pungasinan",
            "Puro"
        ]
    ],
    "San Mateo" => [
        "postal_code" => "1850",
        "barangays" => [
            "Ampid",
            "Anyaya",
            "Aplaya",
            "Balagtas",
            "Balantian",
            "Balao",
            "Balas",
            "Baraang",
            "Bario",
            "Baryang",
            "Batasan",
            "Batingin",
            "Bauang",
            "Bauan",
            "Baya",
            "Bayabas",
            "Bayanan",
            "Bayati",
            "Bayongan",
            "Bayugan",
            "Binabaan",
            "Binambangan",
            "Binang",
            "Binanog",
            "Binisig",
            "Binitin",
            "Bino",
            "Binitawan",
            "Binitnon",
            "Bintag",
            "Biray",
            "Bislig",
            "Bita",
            "Bitak",
            "Bitbit",
            "Bulo",
            "Buma",
            "Bumabak",
            "Bumacay",
            "Bumading",
            "Bumagao",
            "Bumagay",
            "Bumahan",
            "Bumakang",
            "Bumalabnab",
            "Bumalding",
            "Bumaling",
            "Bumandang",
            "Bumandil",
            "Bumanta",
            "Bumantay",
            "Bumaon",
            "Bumaribo",
            "Bumargao",
            "Bumaring",
            "Bumasbas",
            "Bumasing",
            "Bumasoc",
            "Bumastas",
            "Bumasud",
            "Bumata",
            "Bumatangay",
            "Bumataon",
            "Bumatay",
            "Bumatibo",
            "Bumatubig",
            "Bumaulan",
            "Bumayon",
            "Bumayyani",
            "Bumayung",
            "Bumba",
            "Bumbahan",
            "Bumbalong",
            "Bumbang",
            "Bumbasag",
            "Bumbat",
            "Bumbayan",
            "Bumbilao",
            "Bumbo",
            "Bumbog",
            "Bumbong",
            "Bumbot",
            "Bumbunga",
            "Bumbungan",
            "Bumbuyan",
            "Bumbuying",
            "Bumbuyon",
            "Bumbuytoy",
            "Bumbuytoy"
        ]
    ],
    "Tanay" => [
        "postal_code" => "1980",
        "barangays" => [
            "Ampid",
            "Amlahan",
            "Alquezar",
            "Bakod",
            "Bangkaan",
            "Banot",
            "Bantas",
            "Banyan",
            "Baraka",
            "Baras",
            "Barbahan",
            "Barbang",
            "Barbasan",
            "Barber",
            "Barbing",
            "Barcena",
            "Bardang",
            "Barginan",
            "Bargis",
            "Bargod",
            "Bargolohon",
            "Bargon",
            "Bargud",
            "Bariac",
            "Bariage",
            "Barial",
            "Bariangit",
            "Bariang",
            "Bariao",
            "Bariba",
            "Baribang",
            "Baribaw",
            "Baribo",
            "Baribo",
            "Baribod",
            "Baribong",
            "Baribus",
            "Baribyok",
            "Barican",
            "Baricod",
            "Baricot",
            "Baridad",
            "Baridos",
            "Barifen",
            "Barigan",
            "Barigbay",
            "Barigbig",
            "Bariges",
            "Barigid",
            "Barihaw",
            "Bariho",
            "Bariis",
            "Bariitaw",
            "Barijaw",
            "Barijil",
            "Barijod",
            "Barijug",
            "Barikan",
            "Barikis",
            "Bariklit",
            "Bariknod",
            "Barikpo",
            "Barikrad",
            "Barikto",
            "Barikugan",
            "Barikung",
            "Barikusi",
            "Barilam",
            "Barilang",
            "Barilao",
            "Barilat",
            "Barilaway",
            "Barilayad",
            "Barilbad",
            "Barilbang",
            "Barilbay",
            "Barilbid",
            "Barilbig",
            "Barilbil",
            "Barilbod",
            "Barilbon",
            "Barilbot",
            "Barilbud",
            "Barilbug",
            "Barilbuhay",
            "Barilbukid",
            "Barilbukod",
            "Barilbul",
            "Barilbula",
            "Barilbulag",
            "Barilbulalao",
            "Barilbulan",
            "Barilbulanao",
            "Barilbulangan",
            "Barilbulangi",
            "Barilbulangin",
            "Barilbulanglac",
            "Barilbulanglan",
            "Barilbulao",
            "Barilbulat",
            "Barilbulatao",
            "Barilbulaw",
            "Barilbulay",
            "Barilbulayon",
            "Barilbuld",
            "Barilbuldin",
            "Barilbuldon",
            "Barilbuldong",
            "Barilbule",
            "Barilbulian",
            "Barilbuliang",
            "Barilbuliangan",
            "Barilbulic",
            "Barilbulig",
            "Barilbuligan",
            "Barilbulin",
            "Barilbulingo",
            "Barilbulio",
            "Barilbuliod",
            "Barilbuliong",
            "Barilbulis",
            "Barilbulit",
            "Barilbuliwan",
            "Barilbuliyaw",
            "Barilbuliyong",
            "Barilbuliyong"
        ]
    ],
    "Taytay" => [
        "postal_code" => "1900",
        "barangays" => [
            "Bagong Nayon",
            "Bagpag",
            "Bakal",
            "Balanoy",
            "Balaring",
            "Balikat",
            "Balimbing",
            "Balindog",
            "Baliti",
            "Balitoc",
            "Balituran",
            "Baliwasan",
            "Baliyasa",
            "Baliwasan",
            "Baliyasing",
            "Baliwatasan",
            "Baliwig",
            "Baliwigang",
            "Baliyuan",
            "Baliwugan",
            "Baliwyag",
            "Baliyong",
            "Baliyot",
            "Baliyong",
            "Baliyuran",
            "Baliyurin",
            "Baliyutaw",
            "Baljis",
            "Balkis",
            "Balmod",
            "Balmot",
            "Balnad",
            "Balnud",
            "Balod",
            "Baloding",
            "Balogan",
            "Balogang",
            "Baloging",
            "Baloging",
            "Baloging",
            "Balood",
            "Balongguinhawa",
            "Balonggulong",
            "Balonggon",
            "Balongibi",
            "Balongibig",
            "Balongibnon",
            "Balongidog",
            "Balongilig",
            "Balongiloc",
            "Balongimas",
            "Balongimuran",
            "Balongina",
            "Balonginan",
            "Balongindac",
            "Balongindang",
            "Balongindao",
            "Balongindeg",
            "Balongindig",
            "Balongindoc",
            "Balongindod",
            "Balongindogan",
            "Balongindoi",
            "Balongindog",
            "Balongindokad",
            "Balongindon",
            "Balongindong",
            "Balongindong",
            "Balongindongan",
            "Balongindoog",
            "Balongindop",
            "Balongindog",
            "Balongindom",
            "Balongindos",
            "Balongindot",
            "Balongindow",
            "Balongindoy",
            "Balongindug",
            "Balongindum",
            "Balonginday",
            "Balongindayan"
        ]
    ],
    "Tetuan" => [
        "postal_code" => "1911",
        "barangays" => [
            "Banaba",
            "Banayan",
            "Banaybanay",
            "Bandi",
            "Bandian",
            "Bandid",
            "Bandidnon",
            "Bandidnong",
            "Bandigon",
            "Bandig",
            "Bandigan",
            "Bandiganan",
            "Bandiganay",
            "Bandigano",
            "Bandigansay",
            "Bandiganyan",
            "Bandigat",
            "Bandige",
            "Bandiged",
            "Bandigilan",
            "Bandigini",
            "Bandigira",
            "Bandigiring",
            "Bandigit",
            "Bandigitan",
            "Bandigiw",
            "Bandigod",
            "Bandigon",
            "Bandigong",
            "Bandigot",
            "Bandiguan",
            "Bandigud",
            "Bandiguhan",
            "Bandiguhang",
            "Bandiguing",
            "Bandiguis",
            "Bandi"
        ]
    ]
];

function getCitiesInRizal() {
    global $rizal_locations;
    return array_keys($rizal_locations);
}

function getBarangaysByCity($city) {
    global $rizal_locations;
    return isset($rizal_locations[$city]) ? $rizal_locations[$city]['barangays'] : [];
}

function getPostalCodeByCity($city) {
    global $rizal_locations;
    return isset($rizal_locations[$city]) ? $rizal_locations[$city]['postal_code'] : '';
}
?>
